services:
  db:
    image: mongo:latest
    container_name: movie_app_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  movie-api:
    build:
      context: ./Backend/movie-app-go
      dockerfile: Dockerfile
    container_name: movie_app_api
    env_file:
      - ./Backend/movie-app-go/.env
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@db:27017/${MONGO_DB_NAME}?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./Backend/movie-app-go/.env:/app/.env

volumes:
  mongo_data:
